### PR TITLE
feat(scoring): M2 — static finding-score modifiers

### PR DESCRIPTION
**Pull request by michaelweber**
## Summary

Milestone 2 of the finding-scoring design: a pluggable, YAML-driven scoring engine that adjusts a finding's base score based on **static** modifiers (no network, no HTTP). Layers cleanly on top of M1's `types.Score` scaffolding and does not change any output format schemas.

- New package `pkg/scoring/` mirrors `pkg/rule/` conventions (`NewLoader`, `NewLoaderWithFS`, `LoadBuiltinScorers`, `//go:embed scorers/*.yaml`).
- Three static DSL leaves: `match_group` (regex against a named capture), `surrounding_context_contains` (substring in snippet), `match_length` (gt/lt/eq).
- Two modifier kinds: `delta: ±N` and `set_score: N`. Evaluation = priority DESC, YAML ASC on ties. `set_score` replaces, later deltas accumulate. Final clamped to [0,100], severity recomputed via the existing `types.SeverityForScore`.
- Engine wired into `runScan` at the finding-creation hook (`cmd/titus/scan.go:293`), called exactly once per unique finding, before `tx.AddFinding`.
- Malformed scorer YAML or bad regex at load time = hard startup error (fail fast). Runtime condition-evaluation errors = log warning, skip modifier, finding keeps its running score.

## Initial scorer YAMLs

- **`pkg/scoring/scorers/aws.yaml`** — targets `np.aws.1` (AWS API Key) and `np.aws.6` (AWS API Credentials combo). AKIA long-term → `+10`; ASIA session token → `-10`; AIDA identifier (not a credential) → `set_score: 10`.
- **`pkg/scoring/scorers/github.yaml`** — targets `np.github.7` (GitHub fine-grained PAT). `github_pat_` prefix → `-10` (fine-grained tokens are scoped; classic/OAuth PATs are inherently broader).

## Explicit M2 exclusions (deferred to M3/M4)

- HTTP / dynamic modifiers (`http:` + `fires_when:` blocks)
- `--score-scope` CLI flag
- HTTP response cache, per-modifier timeout, per-finding budget
- Custom Go scorers (AWS SigV4 + IAM enumeration, go-github org/team reasoning)
- Compound condition operators (`all:` / `any:` / `not:`)
- Cross-match aggregation (engine currently scores against the triggering match only)

## Design and plan references

- Design doc (gitignored working copy): restored from `5ddf1f8:docs/plans/2026-04-22-finding-scoring-design.md`
- Implementation plan: `.claude/.output/plans/2026-04-23-181916-m2-static-modifiers/` (PLAN.md + 3 phase files + verified-findings.md) — gitignored, developer-local
- Linear: LAB-2431 (child of LAB-2430, grandchild of LAB-14)

## Test plan

- [x] `make test` — 18 packages, 1106 tests green
- [x] `go vet ./...` — clean
- [x] `go build ./...` — clean
- [x] `pkg/scoring/` unit tests: 49 tests total
  - 27 condition-leaf subtests (`match_group`, `surrounding_context_contains`, `match_length`)
  - 9 loader rejection tests covering all malformed-YAML cases
  - 10 engine subtests covering priority DESC, YAML ASC tie-break, delta accumulation, set_score replacement, later-delta-after-set_score, clamp low, clamp high, severity recomputation, empty modifiers, condition-error-skips-modifier
- [x] Golden JSON test for a finding with fired `Applied` modifiers
- [x] Manual smoke test against a fixture containing both an AKIA key and a `github_pat_` token — both findings emit non-empty `Applied[]` with expected modifier names and updated Final scores.

## Concurrency

`Engine.Score` has no post-construction mutable state. `scorers` is set once in `NewEngine`; all per-call state (`current`, `ordered`, `score`) is local. Safe for concurrent calls from multiple scan workers.

## Commit structure

19 commits in three tagged phases:

- Phase 0 — scaffolding + DSL leaves (6 commits: `98d5c54`..`961326c`)
- Phase 1 — loader + engine (7 commits: `84b6f9a`..`9dcc96e`, ending with `phase-1-complete` marker)
- Phase 2 — integration + YAMLs + golden (5 commits: `fd5e515`..`a238ec2`)
- Fix surfaced by smoke test: `4f512bd` — scorer must target both `np.aws.1` and `np.aws.6`

Each implementation commit follows TDD: failing test → implement → green.

## Out of scope (do not land here)

- No changes to SARIF, JSON, or human report formats (M1 schema already exposes `score.applied`; M2 just populates it).
- No new CLI flags.
- No changes to `pkg/validator/` (its HTTP schema is reserved for M3 to reuse).

### CODE REVIEW

**Comment by michaelweber** [comment]
## New: `--accessibility` scan-context modifier

Added a scan-level severity modifier that reduces all finding scores by 25 points when the code being scanned is **private** (not world-readable).

### Rationale

A secret found in a **public** repo is already visible to anyone on the internet — that's maximum exposure, so the base score stands. A secret in a **private** repo is only accessible to members with repo access — meaningfully lower risk — so a flat -25 delta is applied to every finding's score.

### CLI

```bash
# Explicit control
titus scan ./myrepo --accessibility private   # always apply -25
titus scan ./myrepo --accessibility public    # never apply -25

# Auto-detect (default)
titus scan ./myrepo                            # tries to detect, defaults to private
GITHUB_TOKEN=ghp_xxx titus scan ./myrepo       # uses token to call GitHub API for visibility
```

### Auto-detection logic (when `--accessibility auto`, which is the default)

1. Check if the scan target is a git repo with a `github.com` remote
2. If yes, call `GET /repos/{owner}/{repo}` using `GITHUB_TOKEN` env var if set
3. If the API returns `"private": true` → private; `"private": false` → public
4. If any step fails (not a git repo, non-GitHub remote, API error, no token for private repo) → assume **private** with an informational message:
   `[info] could not determine repo accessibility via GitHub API (...); assuming private`

### Score effect — visible in output

The modifier appears in `Score.Applied` so it's fully auditable:

```json
{
  "Score": {
    "Final": 33,
    "Base": 48,
    "SuggestedSeverity": "low",
    "Applied": [
      {"Name": "akia-long-term", "Scorer": "aws-key-scope", "Kind": "delta", "Value": 10, "Priority": 100},
      {"Name": "code-accessibility", "Scorer": "scan-context", "Kind": "delta", "Value": -25, "Priority": 0}
    ]
  }
}
```

AWS key base (48) + AKIA long-term modifier (+10) + private-code context (-25) = **33 (low)**.

### What's NOT included (defer to M3)

- Auto-detection for GitLab, Bitbucket, or other remotes (only GitHub API is implemented)
- Per-file accessibility (single scan-level value applies uniformly)
- The `titus github` subcommand doesn't yet expose `--accessibility` (trivial to add once PR merges)

### Commit

`802758e` — `feat(scan): --accessibility modifier for scan-context severity adjustment`

### Tests

- `TestResolveAccessibility_ExplicitFlags` — public/private flags resolve correctly
- `TestResolveAccessibility_AutoFallsBackToPrivate` — non-git directory defaults to private
- `TestGithubRepoPattern` — regex correctly parses https and ssh GitHub URLs
- `TestApplyAccessibilityModifier_AppliesPenalty` — 80 → 55, severity critical → medium
- `TestApplyAccessibilityModifier_ClampsToZero` — 10 + (-25) clamps to 0
- `TestApplyAccessibilityModifier_NilSafe` — no panic on nil score

1,119 tests pass across 18 packages.

**Comment by michaelweber** [comment]
## CI fix: rebased onto main after PR #201 merge

The CI failures were caused by a silent merge conflict introduced when PR #201 (timeout retry mechanism) was merged to main after this branch diverged.

**Root cause:** PR #201 added `drainTimedOutMatches()` which called `synthesizeBaseScore(rule)` for scoring in the retry path. The M2 branch had removed `synthesizeBaseScore` and replaced it with `engine.Score()`. Git saw no textual conflict (different call sites), but the referenced function was undefined — causing the `undefined: synthesizeBaseScore` error at CI time.

**Fix (`c574fcc`):** Rebased onto current main (`7acafb6`). Updated `drainTimedOutMatches` to accept `engine scoringEngineInterface` as a parameter and use `engine.Score()` in the retry path, consistent with how `runScan`'s parallel worker path scores findings. All three call sites (`runScan`, `runRepoScan`, `runS3Scan`) updated to pass their engine.

**govulncheck failures:** 14 pre-existing dependency vulnerabilities (Go stdlib, go-git, lzma). None in code introduced by this PR — pre-date this branch.

Now passing: `go build ./...`, `go build -tags vectorscan ./...`, `go vet ./...`, 1131 tests.
